name: Commit Notification
on:
  push:
    branches:
      - main
jobs:
  notify:
    runs-on: windows-latest
    steps:
      - name: Check commit count
        run: |
          COUNT=$(git rev-list --count HEAD)
          if (( $COUNT % 02 == 0 )); then
            echo "This is commit number $COUNT" | mail -s "02th Commit Notification" ${GIT_AUTHOR_EMAIL}
          fi
