name: Git Commit Alert

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config --global user.email "arjunsajeev45@gmail.com"
          git config --global user.name "Your Name"
      - name: Install sendmail
        run: sudo apt-get update && sudo apt-get install -y sendmail
      - name: Send email notification
        run: |
          echo "A new commit has been pushed to the repository." | mail -s "Git Commit Alert" arjunsajeev45@gmail.com
